### ISSUE TITLE
Deploying archive results in error

### ISSUE THREAD

**Issue by jozefizso** [PowerShell/PSDscResources#67]
I'm using PSDscResources 2.7.0 to configure my server - I deploy a website from a ZIP archive.

Error: **PowerShell DSC resource MSFT_Archive  failed to execute Set-TargetResource functionality with error message: System.InvalidOperationException: An error occurred while attempting copy from the archive to the destination path C:\inetpub\fogbugz\Accessories\API\.**

```
VERBOSE: [FB-MS01-LAB]: LCM:  [ Start  Resource ]  [[Archive]FogBugzDistZip]
VERBOSE: [FB-MS01-LAB]: LCM:  [ Start  Test     ]  [[Archive]FogBugzDistZip]
VERBOSE: [FB-MS01-LAB]:                            [[Archive]FogBugzDistZip] Retrieving the state of the archive with path C:\install\FogBugz-8.8.55.zip and
destination C:\inetpub\fogbugz...
VERBOSE: [FB-MS01-LAB]:                            [[Archive]FogBugzDistZip] A directory already exists at the destination path C:\inetpub\fogbugz.
VERBOSE: [FB-MS01-LAB]:                            [[Archive]FogBugzDistZip] Testing if the archive at the destination path C:\inetpub\fogbugz exists...
VERBOSE: [FB-MS01-LAB]:                            [[Archive]FogBugzDistZip] Opening the archive at path C:\install\FogBugz-8.8.55.zip...
VERBOSE: [FB-MS01-LAB]:                            [[Archive]FogBugzDistZip] An item with the same name as the archive entry exists at the destination path
C:\inetpub\fogbugz\Accessories\.
VERBOSE: [FB-MS01-LAB]:                            [[Archive]FogBugzDistZip] The item at the destination path C:\inetpub\fogbugz\Accessories\ has the same name as
 a file archive entry but is not a file.
VERBOSE: [FB-MS01-LAB]:                            [[Archive]FogBugzDistZip] Closing the archive at path C:\install\FogBugz-8.8.55.zip...
VERBOSE: [FB-MS01-LAB]:                            [[Archive]FogBugzDistZip] The archive at path C:\install\FogBugz-8.8.55.zip does not exist at the destination
C:\inetpub\fogbugz.
VERBOSE: [FB-MS01-LAB]:                            [[Archive]FogBugzDistZip] Testing whether or not the state of the archive with path
C:\install\FogBugz-8.8.55.zip and destination C:\inetpub\fogbugz matches the desired state...
VERBOSE: [FB-MS01-LAB]: LCM:  [ End    Test     ]  [[Archive]FogBugzDistZip]  in 0.2050 seconds.
VERBOSE: [FB-MS01-LAB]: LCM:  [ Start  Set      ]  [[Archive]FogBugzDistZip]
VERBOSE: [FB-MS01-LAB]:                            [[Archive]FogBugzDistZip] Setting the state of the archive with path C:\install\FogBugz-8.8.55.zip and
destination C:\inetpub\fogbugz...
VERBOSE: [FB-MS01-LAB]:                            [[Archive]FogBugzDistZip] A directory already exists at the destination path C:\inetpub\fogbugz.
VERBOSE: [FB-MS01-LAB]:                            [[Archive]FogBugzDistZip] Expanding the archive at C:\install\FogBugz-8.8.55.zip to the destination
C:\inetpub\fogbugz...
VERBOSE: [FB-MS01-LAB]:                            [[Archive]FogBugzDistZip] Opening the archive at path C:\install\FogBugz-8.8.55.zip...
VERBOSE: [FB-MS01-LAB]:                            [[Archive]FogBugzDistZip] An item with the same name as the archive entry exists at the destination path
C:\inetpub\fogbugz\Accessories\.
VERBOSE: [FB-MS01-LAB]:                            [[Archive]FogBugzDistZip] Overwriting the item at the path C:\inetpub\fogbugz\Accessories\...
VERBOSE: [FB-MS01-LAB]:                            [[Archive]FogBugzDistZip] Copying the corresponding archive entry to the path
C:\inetpub\fogbugz\Accessories\...
VERBOSE: [FB-MS01-LAB]:                            [[Archive]FogBugzDistZip] Opening the archive entry Accessories/...
VERBOSE: [FB-MS01-LAB]:                            [[Archive]FogBugzDistZip] Closing the archive at path C:\install\FogBugz-8.8.55.zip...
VERBOSE: [FB-MS01-LAB]: LCM:  [ End    Set      ]  [[Archive]FogBugzDistZip]  in 0.1250 seconds.
PowerShell DSC resource MSFT_Archive  failed to execute Set-TargetResource functionality with error message: System.InvalidOperationException: An error occurred
while attempting copy from the archive to the destination path C:\inetpub\fogbugz\Accessories\. ---> System.Management.Automation.MethodInvocationException:
Exception calling ".ctor" with "2" argument(s): "The filename, directory name, or volume label syntax is incorrect.
" ---> System.IO.IOException: The filename, directory name, or volume label syntax is incorrect.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions
options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean
bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   --- End of inner exception stack trace ---
   at System.Management.Automation.DotNetAdapter.AuxiliaryConstructorInvoke(MethodInformation methodInformation, Object[] arguments, Object[] originalArguments)
   at System.Management.Automation.DotNetAdapter.ConstructorInvokeDotNet(Type type, ConstructorInfo[] constructors, Object[] arguments)
   at Microsoft.PowerShell.Commands.NewObjectCommand.CallConstructor(Type type, ConstructorInfo[] constructors, Object[] args)
   --- End of inner exception stack trace ---
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
```

**Comment by jozefizso** [comment]
When I switch to the default `PSDesiredStateConfiguration` and its Archive on Windows Server 2016 file is unzipped correctly.

**Comment by kwirkykat** [comment]
@jozefizso I believe this line shows the problem `Opening the archive entry Accessories/...`
This resource doesn't handle forward slashes well at the moment, but it should.
I'm looking at it.
